<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AuthTest extends TestCase
{
    use RefreshDatabase, DatabaseMigrations;
    /**
     * A basic unit test example.
     *
     * @return void
     */
    protected $register;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->register = $this->postJson(route('signup'), ['name' => 'Sally'
            ,'password' => 'longmoney2010', 'email' => 'infinitypaul@ace.com']);
    }

    public function testExample()
    {
        $this->assertTrue(true);
    }

    public function testIfWeCanCreateAnAccount(){

        $this->register
            ->assertStatus(201)
            ->assertJson([
                'data' => [
                    'email' => true
                ]
            ]);
    }

    public function testUserCanLogin(){

        $response = $this->postJson(route('signin'), [
            'password' => 'longmoney2010', 'email' => 'infinitypaul@ace.com']);
        $response
            ->assertStatus(200)
            ->assertJson([
                'data' => [
                    'email' => true
                ]
            ]);
    }
}
